myProject/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.category, name='category'),
    path('cart/', views.cart_view, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_product, name='add_to_cart'),
    path('remove-from-cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('clear/', views.clear_cart, name='clear_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('profile/', views.profile, name='profile'),
    path('chat/', views.chat, name='chat'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
]

myProject/messenger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'messenger'

urlpatterns = [
    path('', views.indexMessenger, name='index'),
    path('chat_view', views.chat_view, name='chat_view'),
    path('chat/<int:chat_id>/', views.chat_view, name='chat_view'),
    path('send_message/<int:chat_id>/', views.send_message, name='send_message'),
    path('admin_chat/', views.admin_chat_view, name='admin_chat'),
]

myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('registration/', include('registration.urls')),
    path('messenger/', include('messenger.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myProject/registration/urls.py
from django.contrib import admin
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import views

app_name = 'registration'

urlpatterns = [
    path('', views.registration_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('logout/', views.logout_view, name='logout'),
]

myProject/main/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/', null=True, blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='products', verbose_name='Категория')
    image = models.ImageField(upload_to='images/', null=True, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Продукты'
        verbose_name = 'Продукт'

    def __str__(self):
        return self.name

myProject/main/forms.py
from PIL.Image import Image
from django.forms import ModelForm, TextInput, ClearableFileInput ,NumberInput, Textarea

from .models import Product, Category


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'image']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control',
                                     'placeholder': 'Введите название продукта'}),
            'price': NumberInput(attrs={'class': 'form-control',
                                        'placeholder': 'Цена продукта'}),
            'description':Textarea(attrs={'class': 'form-control',
                                          'rows': 4, 'cols': 40,'style': 'resize: none',
                                          'placeholder': ' Описание'}),
            'image': ClearableFileInput(attrs={'class': 'form-control-file'}),
        }


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control',
                                     'placeholder': 'Введите название категории'}),
            'image': ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

myProject/main/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from .models import Category, Product

# Отображает главную страницу с перечнем всех товаров.
def index(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'main/index.html', context)

def category(request):
    # Отображает страницу со списком всех категорий.
    categories = Category.objects.all()
    data = {'categories': categories}
    return render(request, 'main/categories.html', data)


# Отображает детальную информацию о товаре по его ID.
def product_detail(request, product_id):

    product = get_object_or_404(Product, id=product_id)
    context = {'product': product}
    return render(request, 'main/product_detail.html', context)


# Добавляет товар в корзину и обновляет общую стоимость.
def add_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = request.session.get('cart', {})
    total = request.session.get('total', 0.0)

    if product_id in cart:
        cart[product_id]['quantity'] += 1
    else:
        cart[product_id] = {'quantity': 1, 'price': product.price}

    total += product.price
    request.session['total'] = total
    request.session['cart'] = cart

    return redirect('main:cart')

# Отображает содержимое корзины и общую стоимость.
def cart_view(request):
    cart = request.session.get('cart', {})
    total = request.session.get('total', 0.0)
    product_ids = cart.keys()
    products = Product.objects.filter(id__in=product_ids)

    return render(request, 'main/cart.html', {
        'cart': cart,
        'products': products,
        'total': total
    })

def remove_from_cart(request, product_id):
    # Удаляет товар из корзины и обновляет общую стоимость.
    product = get_object_or_404(Product, id=product_id)
    cart = request.session.get('cart', {})
    total = request.session.get('total', 0.0)

    product_id_str = str(product_id)
    # Проверяет, является ли значение словарем в cart
    if product_id_str in cart:
        if isinstance(cart[product_id_str], dict):
            total -= cart[product_id_str]['quantity'] * cart[product_id_str]['price']
            del cart[product_id_str]
            request.session['total'] = total
        else:
            # Отладочное сообщение
            print(f"Unexpected type in cart: {type(cart[product_id_str])}")

    request.session['cart'] = cart

    return redirect('main:cart')

def clear_cart(request):
    # Очищает корзину и общую стоимость в сессии.
    request.session.pop('cart', None)
    request.session.pop('total', None)
    return redirect('main:cart')

def checkout(request):
    # Имитирует процесс покупки и очищает корзину.
    cart = request.session.get('cart', {})
    total = request.session.get('total', 0.0)

    if not cart:
        messages.error(request, "Ваша корзина пуста!")
        return redirect('main:cart')

    # Создание заказа, интеграция с платежной системой и т.д.

    # Очистить корзину
    request.session.pop('cart', None)
    request.session.pop('total', None)

    return render(request, 'main/checkout.html', {
        'total': total,
    })

@login_required
def profile(request):
    # Отображает страницу профиля пользователя.
    user = request.user
    data = {'user': user}
    return render(request, 'main/profile.html', data)

def chat(request):
    # Отображает страницу чата.
    return render(request, 'main/chat.html')

myProject/main/templates/main/cart.html
{% extends 'main/layout.html' %}\
{% block title %}Корзина{% endblock %}



{% block content %}
{% load get_item %}
{% load static %}
    <h1>Корзина</h1>
    {% if products %}

        <ul>
            {% for product in products %}
                <div class="cartItemSpan"><li><img
                        class="productInCartImg" src="{{product.image.url}}">
                    {{ product.name }} -  {{ product.price }} $

                    <a href="{% url 'main:remove_from_cart' product.id %}">
                    <img class="trashLogo" src="{% static 'images/trash.png' %}"></a>
                </li>
                <hr></div>
            {% endfor %}
            <h2>Итого: ${{ total|floatformat:2 }}</h2><a href="{% url 'main:checkout' %}" class="btn btn-success"> Покупка </a>
                <a href="{% url 'main:clear_cart' %}"> Очистка</a>
        </ul>

    {% else %}
        <p>Ваша корзина пуста.</p>
    {% endif %}
{% endblock %}

myProject/main/templates/main/categories.html
{% extends 'main/layout.html' %}

{% block title %}Категории{% endblock %}

{% block content %}
    <h1>Категории</h1>
<div class="categories-container">
    {% for category in categories %}
        <div class="category-item">
            {% if category.image %}
                <img src="{{ category.image.url }}" alt="{{ category.name }}">
            {% else %}
                <p>No image available</p>
            {% endif %}
            <h5>{{ category.name }}</h5>
        </div>
    {% endfor %}
</div>
{% endblock %}

myProject/main/templates/main/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    Страница чата
</body>
</html>

myProject/main/templates/main/checkout.html
<!DOCTYPE html>
<html>
<head>
    <title>Оформление заказа</title>
</head>
<body>
    <h1>Спасибо за покупку!</h1>
    <p>Вы потратили ${{ total|floatformat:2 }}</p>
    <a href="{% url 'main:cart' %}">Вернуться в корзину</a>
</body>
</html>

myProject/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <div class="main-content">
        {% if user.is_authenticated %}
            <h1>Горячие новинки</h1>
            <div class="trending-products">
                <div class="categories-container">
                    {% for product in products|slice:":2" %}
                        <a href="{% url 'main:product_detail' product_id=product.id %}">
                            <div class="category-item">
                                {% if product.image %}
                                    <img src="{{ product.image.url }}" alt="{{ product.name }}">
                                {% else %}
                                    <p>Изображение недоступно!</p>
                                {% endif %}
                                <p>{{ product.name }}</p>
                                <p>${{ product.price|floatformat:2 }}</p>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>

            {% if user.is_staff %}
                <h2>Панель Администратора</h2>
                <a href="#"><button>Добавить категорию</button></a>
                <a href="#"><button>Добавить товары</button></a>
                <a href="#"><button>Изменить товары</button></a>
            {% else %}
                <h2>Поиск товара</h2>
                <input type="text" placeholder="Search...">
                <h2>Товары</h2>
                <div class="trending-products">
                <div class="categories-container">
                    {% for product in products %}
                        <a href="{% url 'main:product_detail' product_id=product.id %}">
                            <div class="category-item">
                                {% if product.image %}
                                    <img src="{{ product.image.url }}" alt="{{ product.name }}">
                                {% else %}
                                    <p>Изображение недоступно!</p>
                                {% endif %}
                                <p>{{ product.name }}</p>
                                <p>${{ product.price|floatformat:2 }}</p>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        {% else %}
            <h1>Добро пожаловать, Гость!</h1>
            <p>Мы рады видеть вас здесь. Ознакомьтесь с нашим широким
                ассортиментом товаров и наслаждайтесь отличными покупками.</p>
            <p>Чтобы получить максимальную отдачу от нашего сайта, вы можете:</p>
            <ul>
                <li><a href="{% url 'registration:signup' %}"><button
                        style="background-color: green; color: white;">Регистрация</button>
                </a> Создайте аккаунт для просмотра интересного контента!</li>
            </ul>
        {% endif %}
    </div>
{% endblock %}

myProject/main/templates/main/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    {% block stylesheet %} {% endblock %}
    </head>
<body>
    {% load static %}
    <header class="header">
        <nav class="nav-menu">
            <a href="{% url 'main:index' %}">Магазин</a>
            {% if user.is_superuser %}<a href="{% url 'messenger:admin_chat' %}">Чат/Помощь</a> {% else %}<a href="{% url 'messenger:chat_view' %}">Чат/Помощь</a> {% endif %}

        </nav>
        <div class="profile-buttons">
            {% if user.is_authenticated %}
                <div class="logos">
                <a href="{% url 'main:profile' %}"><img class="cartlogo" src="{% static 'images/profile.png' %}"></a>
                <a href="{% url 'main:cart' %}"><img class="cartlogo" src="{% static 'images/shopping-cart.png' %}"></a></div>
                <form action="{% url 'registration:logout' %}" method="post" class="d-inline">
                {% csrf_token %}
                <input type="hidden" name="refresh_token" value="{{ refresh_token }}">
                <a class="logoutbut" href="{% url 'registration:logout' %}"><button type="submit" class="btn btn-danger">Logout</button></a>
                </form>
            {% else %}
                <a href="#"><img src="{% static 'images/cart.svg' %}"></a>
                <a href="{% url 'registration:login' %}" ><button class="btn btn-primary">Login</button></a>
            {% endif %}
        </div>
    </header>

    {% block content %}
    {% endblock %}

    <footer class="footer">
        @ 2024 Big Company Inc.
    </footer>
</body>
</html>

myProject/main/templates/main/product_detail.html
{% extends 'main/layout.html' %}

{% block title %} {% endblock %}

{% block content %}

    <div class="product-detail">
        <h1>{{ product.name }}</h1>
        {% if product.image %}
            <img class="product_image" src="{{ product.image.url }}" alt="{{ product.name }}">
        {% else %}
            <p>No image available</p>
        {% endif %}
        <p class="price">${{ product.price }}</p>
        <p>{{ product.description }}</p>
        <form action="{% url 'main:add_to_cart' product.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">В корзину</button>
                </form>
    </div>
{% endblock %}

myProject/main/templates/main/profile.html
{% extends 'main/layout.html' %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
    <div class="profile-container">
        <h1>Профиль пользователя</h1>
        <div class="profile-info">
            <p><strong>Имя пользователя:</strong> {{ user.username }}</p>
            <p><strong>Имя:</strong> {{ user.first_name }}</p>
            <p><strong>Фамилия:</strong> {{ user.last_name }}</p>
            <p><strong>Номер телефона:</strong> +77479100321</p>
        </div>
        <div class="profile-actions">
            <a href="#" class="btn btn-primary">Редактировать профиль</a>
            <a href="{% url 'main:index'  %}" class="btn btn-secondary">Назад на главную</a>
        </div>
    </div>
{% endblock %}