myProject/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.category, name='category'),
    path('cart/', views.cart_view, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_product, name='add_to_cart'),
    path('remove-from-cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('clear/', views.clear_cart, name='clear_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('profile/', views.profile, name='profile'),
    path('chat/', views.chat, name='chat'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
]

myProject/messenger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'messenger'

urlpatterns = [
    path('', views.indexMessenger, name='index'),
    path('chat_view', views.chat_view, name='chat_view'),
    path('chat/<int:chat_id>/', views.chat_view, name='chat_view'),
    path('send_message/<int:chat_id>/', views.send_message, name='send_message'),
    path('admin_chat/', views.admin_chat_view, name='admin_chat'),
]

myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('registration/', include('registration.urls')),
    path('messenger/', include('messenger.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myProject/messenger/models.py
from django.conf import settings
from django.db import models



class Chat(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_chats', null=True)
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='admin_chats',blank=True, null=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
class Messenger(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sender} - {self.created_at}'

myProject/messenger/forms.py
from django import forms
from .models import Messenger, Chat


class MessageForm(forms.ModelForm):
    class Meta:
        model = Messenger
        fields = ['message']
        widgets = {
            'message': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Введите ваше сообщение...'}),
        }

myProject/messenger/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .forms import MessageForm
from .models import Messenger, Chat


def indexMessenger(request):
    return render(request, 'messenger/index.html')


@login_required
def chat_view(request):
    User = get_user_model()

    admin = get_object_or_404(User, is_superuser=True)

    # Поиск существующего диалога
    chat = Chat.objects.filter(
        Q(user=request.user, admin=admin) |
        Q(user=admin, admin=request.user)
    ).first()

    # Если диалог не найден, создаем новый
    if not chat:
        chat = Chat.objects.create(
            user=request.user,
            admin=admin,
            name=f"Chat between {request.user.username} and {admin.username}"
        )

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.chat = chat
            message.sender = request.user
            message.save()
            return redirect('messenger:chat_view')
    else:
        form = MessageForm()

    messages = Messenger.objects.filter(chat=chat)

    context = {
        'user': request.user,
        'chat': chat,
        'messages': messages,
        'form': form
    }
    return render(request, 'messenger/index.html', context)


@login_required

def admin_chat_view(request):
    admin = get_object_or_404(get_user_model(), is_superuser=True)
    chats = Chat.objects.filter(admin=admin)

    # Получение сообщений для отображения
    messages = Messenger.objects.filter(chat__in=chats).order_by('created_at')

    context = {
        'admin': admin,
        'chats': chats,
        'messages': messages,
    }
    return render(request, 'messenger/admin_chat.html', context)


def is_admin(user):
    return user.is_superuser

@login_required
def send_message(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id)

    # Пользователь либо админ, либо участник чата
    if request.user != chat.user and not is_admin(request.user):
        return redirect('some_error_page')  # Или другое действие

    if request.method == 'POST':
        message_text = request.POST.get('message')
        if message_text:
            Messenger.objects.create(
                chat=chat,
                sender=request.user,
                message=message_text
            )
        return redirect('messenger:admin_chat_view' if request.user.is_superuser else 'messenger:chat_view',
                        chat_id=chat_id)

myProject/messenger/templates/messenger/admin_chat.html
{% extends 'main/layout.html'  %}

{% block title %} {% endblock %}

{% block content %}
<h1>Чаты с пользователями</h1>

{% for chat in chats %}
    <div class="chat-box">
        <h2>Чат с {{ chat.user.username }}</h2>
        <div class="messages">
            {% for message in chat.messenger_set.all %}
                <p><strong>{{ message.sender.username }}:</strong> {{ message.message }} <i class="time">{{ message.created_at|date:"g:i a" }}</i></p>
            {% endfor %}
        </div>
        <form method="post" action="{% url 'messenger:send_message' chat.id %}">
    {% csrf_token %}
    <input type="text" name="message" placeholder="Введите ваше сообщение...">
    <button type="submit">Отправить</button>
</form>

    </div>
{% endfor %}

{% endblock %}

myProject/messenger/templates/messenger/chat_view.html
{% extends 'main/layout.html' %}

{% block title %} Чат {% endblock %}
{% load static %}
{% block stylesheet %} <link rel="stylesheet" href="{% static 'messenger/css/messenger.css' %}">{% endblock %}

{% block content %}
<div class="support"><h3>Чат со службой поддержки</h3> </div>
<div class="chat-container">

    <div class="messages" id="messages">
        {% for message in messages %}
            <p>
                <strong class="{% if message.sender == user %}sender{% else %}receiver{% endif %}">
                    {{ message.sender.username }}:
                </strong>
                {{ message.message }}
                <i class="time">{{ message.created_at|date:"g:i a" }}</i>
            </p>
        {% empty %}
            <p>No messages yet.</p>
        {% endfor %}
    </div>
    <div class="input-container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Send</button>
        </form>
    </div>
</div>
{% endblock %}

myProject/messenger/templates/messenger/index.html
{% extends 'main/layout.html' %}

{% block title %} Чат {% endblock %}
{% load static %}
{% block stylesheet %} <link rel="stylesheet" href="{% static 'messenger/css/messenger.css' %}">{% endblock %}

{% block content %}
<div class="chat-container">
    <div class="messages" id="messages">
        {% for message in messages %}
            <p>
                <strong class="{% if message.sender == user %}sender{% else %}receiver{% endif %}">
                    {{ message.sender.username }}:
                </strong>
                {{ message.message }}
                <i class="time">{{ message.created_at|date:"g:i a" }}</i>
            </p>
        {% empty %}
            <p>No messages yet.</p>
        {% endfor %}
    </div>
    <div class="input-container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Send</button>
        </form>
    </div>
</div>
{% endblock %}